[package]
name = "devkyato/gentree"
description = "A small procedural tree generator I made for Roblox."
version = "0.1.1"
license = "MIT"
authors = ["devkyato"]
realm = "server"
registry = "https://github.com/UpliftGames/wally-index"
repository = "https://github.com/devkyato/GenTree"
include = ["src", "src/**", "default.project.json", "LICENSE"]
exclude = ["**"]

[dependencies]
